import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "./theme/ThemeRegistry";
import { AuthProvider } from "../src/contexts/AuthContext";

import ClientWrapper from "./ui/utils/ClientWrapper";
import { createTheme } from "@mui/material/styles";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Porcigest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`px-3 py-4 ${quicksand.className} md:${quicksand.className} antialiased min-h-screen`}>
        <AuthProvider>
          <ThemeRegistry>
            <ClientWrapper>{children}</ClientWrapper>
          </ThemeRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
