"""Añade relaciones de usuario a todos los modelos para auditoría

Revision ID: 20eb63a203ad
Revises: 7435237c7541
Create Date: 2025-09-22 17:08:16.090489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20eb63a203ad'
down_revision: Union[str, Sequence[str], None] = '7435237c7541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
