"""Creación inicial de tablas

Revision ID: 3b8472aa81e0
Revises: 
Create Date: 2025-08-28 14:30:24.217788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8472aa81e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cerdas_reproductoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_id', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('raza', sa.String(), nullable=True),
    sa.Column('estado_reproductivo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cerdas_reproductoras_codigo_id'), 'cerdas_reproductoras', ['codigo_id'], unique=True)
    op.create_index(op.f('ix_cerdas_reproductoras_id'), 'cerdas_reproductoras', ['id'], unique=False)
    op.create_table('sementales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('raza', sa.String(), nullable=True),
    sa.Column('tasa_fertilidad', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sementales_id'), 'sementales', ['id'], unique=False)
    op.create_index(op.f('ix_sementales_nombre'), 'sementales', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sementales_nombre'), table_name='sementales')
    op.drop_index(op.f('ix_sementales_id'), table_name='sementales')
    op.drop_table('sementales')
    op.drop_index(op.f('ix_cerdas_reproductoras_id'), table_name='cerdas_reproductoras')
    op.drop_index(op.f('ix_cerdas_reproductoras_codigo_id'), table_name='cerdas_reproductoras')
    op.drop_table('cerdas_reproductoras')
    # ### end Alembic commands ###
