"""actualizar_estructura_lotes_engorde

Revision ID: 50449d07d4a4
Revises: 20eb63a203ad
Create Date: 2025-09-29 12:27:10.667093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50449d07d4a4'
down_revision: Union[str, Sequence[str], None] = '20eb63a203ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes_engorde', sa.Column('fecha_inicio', sa.Date(), nullable=False))
    op.add_column('lotes_engorde', sa.Column('numero_cerdos', sa.Integer(), nullable=False))
    op.add_column('lotes_engorde', sa.Column('peso_inicial_promedio', sa.Float(), nullable=True))
    op.add_column('lotes_engorde', sa.Column('peso_actual_promedio', sa.Float(), nullable=True))
    op.drop_column('lotes_engorde', 'cantidad_animales')
    op.drop_column('lotes_engorde', 'peso_promedio_kg')
    op.drop_column('lotes_engorde', 'edad_dias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes_engorde', sa.Column('edad_dias', sa.INTEGER(), nullable=True))
    op.add_column('lotes_engorde', sa.Column('peso_promedio_kg', sa.FLOAT(), nullable=True))
    op.add_column('lotes_engorde', sa.Column('cantidad_animales', sa.INTEGER(), nullable=False))
    op.drop_column('lotes_engorde', 'peso_actual_promedio')
    op.drop_column('lotes_engorde', 'peso_inicial_promedio')
    op.drop_column('lotes_engorde', 'numero_cerdos')
    op.drop_column('lotes_engorde', 'fecha_inicio')
    # ### end Alembic commands ###
