"""Añade relaciones de usuario a todos los modelos para auditoría

Revision ID: 7435237c7541
Revises: f38ebe58c455
Create Date: 2025-09-22 17:02:15.009786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7435237c7541'
down_revision: Union[str, Sequence[str], None] = 'f38ebe58c455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camadas_lechones') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_camadas_lechones_user_id', 'users', ['user_id'], ['id'])
    
    with op.batch_alter_table('cerdas_reproductoras') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cerdas_reproductoras_user_id', 'users', ['user_id'], ['id'])
    
    with op.batch_alter_table('lotes_engorde') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_lotes_engorde_user_id', 'users', ['user_id'], ['id'])
    
    with op.batch_alter_table('sementales') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sementales_user_id', 'users', ['user_id'], ['id'])
    
    with op.batch_alter_table('tratamientos_veterinarios') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tratamientos_veterinarios_user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tratamientos_veterinarios') as batch_op:
        batch_op.drop_constraint('fk_tratamientos_veterinarios_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    
    with op.batch_alter_table('sementales') as batch_op:
        batch_op.drop_constraint('fk_sementales_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    
    with op.batch_alter_table('lotes_engorde') as batch_op:
        batch_op.drop_constraint('fk_lotes_engorde_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    
    with op.batch_alter_table('cerdas_reproductoras') as batch_op:
        batch_op.drop_constraint('fk_cerdas_reproductoras_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    
    with op.batch_alter_table('camadas_lechones') as batch_op:
        batch_op.drop_constraint('fk_camadas_lechones_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
