"""Añade relaciones de usuario a todos los modelos para auditoría

Revision ID: 7435237c7541
Revises: f38ebe58c455
Create Date: 2025-09-22 17:02:15.009786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7435237c7541'
down_revision: Union[str, Sequence[str], None] = 'f38ebe58c455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camadas_lechones', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'camadas_lechones', 'users', ['user_id'], ['id'])
    op.add_column('cerdas_reproductoras', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cerdas_reproductoras', 'users', ['user_id'], ['id'])
    op.add_column('lotes_engorde', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lotes_engorde', 'users', ['user_id'], ['id'])
    op.add_column('sementales', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sementales', 'users', ['user_id'], ['id'])
    op.add_column('tratamientos_veterinarios', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tratamientos_veterinarios', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tratamientos_veterinarios', type_='foreignkey')
    op.drop_column('tratamientos_veterinarios', 'user_id')
    op.drop_constraint(None, 'sementales', type_='foreignkey')
    op.drop_column('sementales', 'user_id')
    op.drop_constraint(None, 'lotes_engorde', type_='foreignkey')
    op.drop_column('lotes_engorde', 'user_id')
    op.drop_constraint(None, 'cerdas_reproductoras', type_='foreignkey')
    op.drop_column('cerdas_reproductoras', 'user_id')
    op.drop_constraint(None, 'camadas_lechones', type_='foreignkey')
    op.drop_column('camadas_lechones', 'user_id')
    # ### end Alembic commands ###
