"""Añade tabla CamadaLechones y relaciones

Revision ID: a97d4416f715
Revises: 3b8472aa81e0
Create Date: 2025-09-02 13:25:46.744782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97d4416f715'
down_revision: Union[str, Sequence[str], None] = '3b8472aa81e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camadas_lechones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('numero_lechones', sa.Integer(), nullable=False),
    sa.Column('peso_promedio_kg', sa.Float(), nullable=True),
    sa.Column('madre_id', sa.Integer(), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['madre_id'], ['cerdas_reproductoras.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['sementales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camadas_lechones_id'), 'camadas_lechones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camadas_lechones_id'), table_name='camadas_lechones')
    op.drop_table('camadas_lechones')
    # ### end Alembic commands ###
