"""Añade tabla LoteEngorde y relaciones

Revision ID: b6fe58ff6e06
Revises: a97d4416f715
Create Date: 2025-09-02 14:09:05.939843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fe58ff6e06'
down_revision: Union[str, Sequence[str], None] = 'a97d4416f715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes_engorde',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id_str', sa.String(), nullable=False),
    sa.Column('cantidad_animales', sa.Integer(), nullable=False),
    sa.Column('edad_dias', sa.Integer(), nullable=True),
    sa.Column('peso_promedio_kg', sa.Float(), nullable=True),
    sa.Column('camada_origen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camada_origen_id'], ['camadas_lechones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_engorde_id'), 'lotes_engorde', ['id'], unique=False)
    op.create_index(op.f('ix_lotes_engorde_lote_id_str'), 'lotes_engorde', ['lote_id_str'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lotes_engorde_lote_id_str'), table_name='lotes_engorde')
    op.drop_index(op.f('ix_lotes_engorde_id'), table_name='lotes_engorde')
    op.drop_table('lotes_engorde')
    # ### end Alembic commands ###
