"""Añade tabla TratamientoVeterinario y relaciones

Revision ID: ffa99c7e44ac
Revises: b6fe58ff6e06
Create Date: 2025-09-02 14:55:07.969498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa99c7e44ac'
down_revision: Union[str, Sequence[str], None] = 'b6fe58ff6e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tratamientos_veterinarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_intervencion', sa.String(), nullable=False),
    sa.Column('medicamento_producto', sa.String(), nullable=True),
    sa.Column('dosis', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('veterinario', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('reproductora_id', sa.Integer(), nullable=True),
    sa.Column('semental_id', sa.Integer(), nullable=True),
    sa.Column('lote_engorde_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_engorde_id'], ['lotes_engorde.id'], ),
    sa.ForeignKeyConstraint(['reproductora_id'], ['cerdas_reproductoras.id'], ),
    sa.ForeignKeyConstraint(['semental_id'], ['sementales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tratamientos_veterinarios_id'), 'tratamientos_veterinarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tratamientos_veterinarios_id'), table_name='tratamientos_veterinarios')
    op.drop_table('tratamientos_veterinarios')
    # ### end Alembic commands ###
